'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cliente
    Public Property Id As Integer
    Public Property Cpf As String
    Public Property Rg As String
    Public Property Data As Nullable(Of Date)
    Public Property Inativo As Nullable(Of Boolean)
    Public Property Nome As String
    Public Property Endereco As String
    Public Property Numero As String
    Public Property Complemento As String
    Public Property Bairro As String
    Public Property Cidade As String
    Public Property Estado As String
    Public Property Usuario As String
    Public Property DataCadastro As Nullable(Of Date)

    Public Overridable Property ClienteContatos As ICollection(Of ClienteContatos) = New HashSet(Of ClienteContatos)
    Public Overridable Property Titulo As ICollection(Of Titulo) = New HashSet(Of Titulo)

End Class
