'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ClienteContatos
    Public Property Id As Integer
    Public Property ClienteId As Nullable(Of Integer)
    Public Property Tipo As String
    Public Property Dados As String
    Public Property Obs As String

    Public Overridable Property Cliente As Cliente

End Class
