'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class FormaPagamento
    Public Property Id As Integer
    Public Property Descricao As String
    Public Property Desconto As Nullable(Of Decimal)
    Public Property Juros As Nullable(Of Decimal)
    Public Property Boleto As Nullable(Of Boolean)

    Public Overridable Property FormaPrazo As ICollection(Of FormaPrazo) = New HashSet(Of FormaPrazo)
    Public Overridable Property Titulo As Titulo

End Class
