'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Produto
    Public Property Id As Integer
    Public Property Codigo As Nullable(Of Integer)
    Public Property Descricao As String
    Public Property Data As Nullable(Of Date)
    Public Property Estoque As Nullable(Of Boolean)
    Public Property Grupo As String
    Public Property Tipo As String
    Public Property Custo As Nullable(Of Decimal)
    Public Property Margem As Nullable(Of Decimal)
    Public Property Preco As Nullable(Of Decimal)
    Public Property Inativo As Nullable(Of Boolean)
    Public Property Usuario As String

    Public Overridable Property VendaRegistros As ICollection(Of VendaRegistros) = New HashSet(Of VendaRegistros)

End Class
