'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class SizexConnectionEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=SizexConnectionEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Cliente() As DbSet(Of Cliente)
    Public Overridable Property ClienteContatos() As DbSet(Of ClienteContatos)
    Public Overridable Property FormaPagamento() As DbSet(Of FormaPagamento)
    Public Overridable Property FormaPrazo() As DbSet(Of FormaPrazo)
    Public Overridable Property Titulo() As DbSet(Of Titulo)
    Public Overridable Property Veiculo() As DbSet(Of Veiculo)
    Public Overridable Property VeiculoRegistros() As DbSet(Of VeiculoRegistros)
    Public Overridable Property Venda() As DbSet(Of Venda)
    Public Overridable Property VendaRegistros() As DbSet(Of VendaRegistros)
    Public Overridable Property Produto() As DbSet(Of Produto)

End Class
