'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Titulo
    Public Property Id As Integer
    Public Property ClienteId As Nullable(Of Integer)
    Public Property FormaId As Nullable(Of Integer)
    Public Property VendaId As Nullable(Of Integer)
    Public Property Tipo As String
    Public Property Pessoa As String
    Public Property Resultado As String
    Public Property VencimentoParc As Nullable(Of Date)
    Public Property Parcelas As Nullable(Of Integer)
    Public Property DiaProxParc As Nullable(Of Integer)
    Public Property Valor As Nullable(Of Decimal)
    Public Property Desconto As Nullable(Of Decimal)
    Public Property Juros As Nullable(Of Decimal)
    Public Property Multa As Nullable(Of Decimal)
    Public Property Documento As String
    Public Property FormaPgmt As String
    Public Property Obs As String

    Public Overridable Property Cliente As Cliente
    Public Overridable Property FormaPagamento As FormaPagamento
    Public Overridable Property Venda As Venda

End Class
