'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VeiculoRegistros
    Public Property Id As Integer
    Public Property VeiculoId As Nullable(Of Integer)
    Public Property DataAbast As Nullable(Of Date)
    Public Property KmAbast As Nullable(Of Integer)
    Public Property Litros As Nullable(Of Decimal)
    Public Property ValorTotal As Nullable(Of Decimal)

    Public Overridable Property Veiculo As Veiculo

End Class
