'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VendaRegistros
    Public Property Id As Integer
    Public Property ProdutoId As Nullable(Of Integer)
    Public Property VendaId As Nullable(Of Integer)
    Public Property Quantidade As Nullable(Of Decimal)
    Public Property ValorUni As Nullable(Of Decimal)

    Public Overridable Property Venda As Venda
    Public Overridable Property Produto As Produto

End Class
